name: Print Message on Push

on:
  push:
    branches:
      - main

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the latest commit on main
        id: main_commit
        run: |
          git fetch origin main
          echo "::set-output name=commit::$(git rev-parse origin/main)"

      - name: Get the latest commit on the PR
        id: pr_commit
        run: echo "::set-output name=commit::${{ github.event.pull_request.head.sha }}"

      - name: Print message
        if: steps.main_commit.outputs.commit != steps.pr_commit.outputs.commit
        run: echo "passou"