name: Print Message on Push

on:
  push:
    branches:
      - main

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the latest commit hash on main
        id: main_commit
        run: |
          git fetch origin main
          echo "::set-output name=hash::$(git rev-parse origin/main)"

      - name: Get the latest commit hash on the PR
        id: pr_commit
        run: |
          echo "::set-output name=hash::${{ github.event.pull_request.head.sha }}"

      - name: Compare commits and print message
        if: steps.main_commit.outputs.hash != steps.pr_commit.outputs.hash
        run: echo "passou"