name: Print Message on Push

on:
  push:
    branches:
      - main

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the latest commit hash on main
        id: main_commit
        run: |
          git fetch origin main
          echo "::set-output name=hash::$(git rev-parse origin/main)"

      - name: Get the latest commit hash on the PR
        id: pr_commit
        run: |
          echo "::set-output name=hash::${{ github.event.pull_request.head.sha }}"

      - name: Check if main commit is an ancestor of PR commit
        id: check_ancestor
        run: |
          git fetch origin main
          if git merge-base --is-ancestor ${{ steps.main_commit.outputs.hash }} ${{ steps.pr_commit.outputs.hash }}; then
            echo "::set-output name=ancestor::true"
          else
            echo "::set-output name=ancestor::false"
          fi

      - name: Print message
        if: steps.check_ancestor.outputs.ancestor == 'false'
        run: echo "passou"