name: Print Message on Push

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the latest commit date on main
        id: main_commit_date
        run: |
          git fetch origin main
          echo "::set-output name=date::$(git log -1 --format=%cI origin/main)"

      - name: Print the commit date
        run: echo "The latest commit date on main is ${{ steps.main_commit_date.outputs.date }}"

      - name: Get the latest commit date on the PR
        id: pr_commit_date
        run: |
          echo "::set-output name=date::$(git log -1 --format=%cI ${{ github.event.pull_request.head.ref }})"

      - name: Print the commit date on the PR
        run: echo "The latest commit date on the PR is ${{ steps.pr_commit_date.outputs.date }}"

      - name: Compare commit dates and print message
        if: steps.main_commit_date.outputs.date < steps.pr_commit_date.outputs.date
        run: echo "passou"